// 13.40 kernel .data offsets.
// Derived from ps5-payload-dev/sdk. Cross-verified against 12.70.

const OFFSET_KERNEL_DATA             = 0x00CB0000;
const OFFSET_KERNEL_ALLPROC          = 0x03589E80;
const OFFSET_KERNEL_SECURITY_FLAGS   = 0x01A49064;
const OFFSET_KERNEL_ROOTVNODE        = 0x03DE7510;
const OFFSET_KERNEL_BUS_DATA_DEVICES = 0x02D481E8;

export {
  OFFSET_KERNEL_DATA,
  OFFSET_KERNEL_ALLPROC,
  OFFSET_KERNEL_SECURITY_FLAGS,
  OFFSET_KERNEL_ROOTVNODE,
  OFFSET_KERNEL_BUS_DATA_DEVICES,
};
